name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PY: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./CI/environment-py38.yml
          extra-specs: python=${{ matrix.PY }}
      - uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          command: build
          args: --release -o dist --find-interpreter
      - name: pip-install
        shell: bash -l {0}
        run: |
          pip install dist/* --no-deps
      - name: test
        shell: bash -l {0}
        run: |
          pytest -v
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

