name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PY: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./CI/environment-py38.yml
          extra-specs: python=${{ matrix.PY }}
      - name: build
        shell: bash -l {0}
        run: |
          maturin build --release --strip -o dist
      - name: pip-install
        shell: bash -l {0}
        run: |
          pip install dist/* --no-deps --force-reinstall
      - name: test
        shell: bash -l {0}
        run: |
          RUST_BACKTRACE=full pytest -v -s
      - name: Upload wheels
        shell: bash -l {0}
        run: |
          anaconda login --username mdurant --password ${{ secrets.ANACONDA_PASSWORD }}
          anaconda upload dist/*
